const route = require('express').Router()
const ops = require('../controllers/operasional')

route.post('/add/:id', ops.addCart)
route.delete('/del/:id', ops.deleteCart)
route.get('/cart', ops.getCartOps)
route.patch('/submit', ops.submitOps)
route.patch('/subfinops', ops.submitOpsFinal)
route.post('/updoc', ops.uploadDocument)
route.patch('/doc', ops.getDocument)
route.patch('/detail', ops.getDetailOps)
route.get('/get', ops.getOps)
route.patch('/ttd', ops.getApproval)
route.get('/docdraft/:name', ops.getDocDraft)
route.patch('/app', ops.approveOps)
route.patch('/reject', ops.rejectOps)
route.patch('/apprev', ops.appRevisi)
route.patch('/update/:id', ops.editOps)
route.patch('/subrev', ops.submitRevisi)
route.patch('/verif', ops.submitVerif)
route.patch('/editvrf/:id', ops.updateDataVerif)
route.patch('/subbayar', ops.submitAjuanBayar)
route.patch('/ttdlist', ops.getApprovalList)
route.patch('/applist', ops.approveListOps)
route.patch('/rejectlist', ops.rejectListOps)

module.exports = route
